### ISSUE TITLE
make test, c++ examples deadlock(?) on OS X 10.9.1, QT 5.1.1,5.2.0

### ISSUE THREAD

**Issue by oliverguenther** [biometrics/openbr#151]
I've experienced indefinite high load in executing both the examples from app/examples and make test from openbr/master

Some background:
openbr/master builds fine on OS X 10.9.1 with both QT 5.1.1. and the most recent release 5.2.0. However, linking against 5.1.1 yields to compiler warnings, as that release does not yet fully support 10.9.

I'm on master, current HEAD (that is, 6e514de344a0bea80ff5e0ac2465cda4fb52c530)

With both QT versions, all examples work fine using the `br` commands and only take a few moments. However, executing their C++ counterparts (e.g., any of app/examples/face_recogntion*.cpp) leads to CPU hogging on all cores indefinitely (cancelled after a few minutes to decrease the fan levels to a human rate). The activity monitor reports the example as non-responding, but the corresponding QTKitServer instance continues to run.

![bildschirmfoto 2014-01-18 um 21 49 13](https://f.cloud.github.com/assets/459462/1948173/0fb317ca-8082-11e3-8538-80f1125d250c.png)

I've interrupted the face_recogntion after ~1min and pasted a backtrace of all threads here: http://pastie.org/8641841

I'm no expert with QT and even less proficient in debugging it, but I'll gladly provide any additional output that might be useful.

**Comment by wincle** [comment]
@mburge Thank you , I have just upgrade my mac, and it happened to me, your solution helped me.
