### ISSUE TITLE
Permissive mode

### ISSUE THREAD

**Issue by imaus10** [biometrics/openbr#236]
I've noticed that when the image input to OpenBR is unpredictable, so there are unpredictable errors. I would like to add a feature to OpenBR that will safely ignore and log these errors. This is critical for a continuous fault-tolerant system.

To that end, I want to introduce a `-permissive` flag that wraps the `Transforms` in a try-catch. This could be a `Transform` itself. That's my first idea; would appreciate input from @jklontz @caotto

**Comment by sklum** [comment]
Going to close this due to inactivity.  @imaus10 is welcome to submit a PR if there is still interest 😄.
