### ISSUE TITLE
Algorithm descriptions for different algorithms?

### ISSUE THREAD

**Issue by herohuyongtao** [biometrics/openbr#264]
What algorithm descriptions should be used if I want to train a face recognition model using Eigenface alone, Fisherface alone and LBP alone in order to perform similar like OpenCV's Eigenface, Fisherface and LBP?

Also, are there any format requirements for the input trained data for different algorithms?

Looking forward to your help. Thanks.

**Comment by sklum** [comment]
If this is still an issue, please post it to the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/openbr-dev).
