### ISSUE TITLE
Compile error (eval.cpp) 

### ISSUE THREAD

**Issue by caotto** [biometrics/openbr#293]
Getting a compile error about ambiguous calls to 'pow' in eval.cpp. This is easily resolved with an explicit cast, but not sure why nobody else has this issue.

Maybe compiler versions? This was with:
Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn)

/Users/caotto/work/openbr/openbr/core/eval.cpp:951:65: error: call to 'pow' is
      ambiguous
  ...if (min(box.width(), box.height()) > sqrt(0.5 * pow(minSize, 2))) {
                                                     ^~~
/usr/include/c++/4.2.1/cmath:364:3: note: candidate function
  pow(double __x, int __i)
  ^
/usr/include/c++/4.2.1/cmath:368:3: note: candidate function
  pow(float __x, int __n)
  ^
/usr/include/c++/4.2.1/cmath:372:3: note: candidate function
  pow(long double __x, int __n)
  ^
/usr/include/math.h:436:15: note: candidate function
extern double pow(double, double);
              ^
/usr/include/c++/4.2.1/cmath:356:3: note: candidate function
  pow(float __x, float __y)
  ^
/usr/include/c++/4.2.1/cmath:360:3: note: candidate function
  pow(long double __x, long double __y)
  ^
/Users/caotto/work/openbr/openbr/core/eval.cpp:976:65: error: call to 'pow' is
      ambiguous
  ...if (min(box.width(), box.height()) < sqrt(0.5 * pow(maxSize, 2))) {
                                                     ^~~
/usr/include/c++/4.2.1/cmath:364:3: note: candidate function
  pow(double __x, int __i)
  ^
/usr/include/c++/4.2.1/cmath:368:3: note: candidate function
  pow(float __x, int __n)
  ^
/usr/include/c++/4.2.1/cmath:372:3: note: candidate function
  pow(long double __x, int __n)
  ^
/usr/include/math.h:436:15: note: candidate function
extern double pow(double, double);
              ^
/usr/include/c++/4.2.1/cmath:356:3: note: candidate function
  pow(float __x, float __y)
  ^
/usr/include/c++/4.2.1/cmath:360:3: note: candidate function
  pow(long double __x, long double __y)
  ^
2 errors generated.

**Comment by JordanCheney** [comment]
I think this can be closed since the move to the new docs. One comment is that the new docs don't include OS information anywhere (i.e we don't say use OSX 10.10 or Ubuntu 14.04) and we probably should. I think that should be a new ticket though
