### ISSUE TITLE
Improved evalLandmarking/plotLandmarking functionality

### ISSUE THREAD

**Issue by sklum** [biometrics/openbr#302]
It would be nice if `plotLandmarking` incorporated some of the new functionality present in `plot`. Specifically, I'd like the PDF to contain:

* A single example with the points drawn and labelled 0-n on the face.
* Tables with mean error, median error, and std. dev. of error for each landmark along with an with the average of these values over all landmarks.
* Mean normalization distance (in pixels)
* Most accurate/least accurate examples.  Here, I'd like images side by side with the ground truth drawn on the left (without labels) and automatically determined on the right (without labels).

**Comment by sklum** [comment]
@bhklein As most of the computation for this is already present in `evalLandmarking`, it's simply a matter of translating things into the proper R calls.  Given your expertise with the `eval` framework and R, do you mind looking into this?  I want to emphasize that this is _not_ a priority.

**Comment by bhklein** [comment]
Sure, I can work on implementing this sometime in the coming weeks.
