### ISSUE TITLE
Lack of user feedback for non-existing transforms or abbrevations

### ISSUE THREAD

**Issue by bklare** [biometrics/openbr#323]
If one tries to run an algorithm that has an invalid transform or abbreviation name, openbr seg faults without a message as to why.

E.g.:
> $ br -algorithm "DoWhatIWant" -enroll in.xml out.xml
> Set algorithm to DoWhatIWant
> Segmentation fault (core dumped)

**Comment by caotto** [comment]
Should be addressed by bd35069
