### ISSUE TITLE
br outputs to console's std_err

### ISSUE THREAD

**Issue by bklare** [biometrics/openbr#325]
The convention for output to the console in openbr is the `qDebug()` function, which outputs to std_err. This seems counter to best practices of output non-error messages to to std_out. This is not a major issue, but makes redirects more difficult.

**Comment by jklontz** [comment]
I think the decision on stdout vs stderr needs to be made on a case by case basis. In general, messages that constitute side-effects should be sent to stderr, and messages that are the primary output of the command should be sent to stdout. The other consideration is making sure not to pollute stdout for cases where OpenBR output is piped into other commands. What output do you have in mind?

**Comment by bklare** [comment]
I agree.  Follow on thoughts:
1. Suggested standard for std_out vs. std_err: (i) anything that results in FTE is std_err (warning level), anything that causes a crash is std_err (error level), and (iii) else, is std_out (normal level).
2. If the text output to std_out is too much, then it should be contained within the `-verbose` flag.  This seems like a separate, but important, debate. We might want to consider introducing a -headless flag (or similar) to indicate piped environemtn.

**Comment by jklontz** [comment]
What's an example of something that is currently stderr that you think should be stdout?

**Comment by bklare** [comment]
Every statement output from a successful run. Not a huge deal but does not
seem to follow a convention I am familiar with.

**Comment by jklontz** [comment]
The only thing I can think of that currently fits that is the output from -eval which I agree should be stdout.

**Comment by jklontz** [comment]
And perhaps anything from `-verbose`?

**Comment by bklare** [comment]
For example, from a slightly different version of the train function in
`helloWorld.sh`. All of this output is to std_err. None of it belongs to
std_err, IMO:

> $ br -algorithm
'Open+Cvt(Gray)+Cascade(FrontalFace)+ASEFEyes+Affine(128,128,0.33,0.45)+CvtFloat+PCA(0.95):Dist(L2)'
-path $DATA -train $METADATA/MEDS/sigset/MEDS_frontal_all.xml Eigenfaces >
out.txt
> Set algorithm to
Open+Cvt(Gray)+Cascade(FrontalFace)+ASEFEyes+Affine(128,128,0.33,0.45)+CvtFloat+PCA(0.95):Dist(L2)
> Set path to /Users/m29389/Data/
> Training on /Users/m29389/Data/metadata//MEDS/sigset/MEDS_frontal_all.xml
to Eigenfaces
> 1216 Training Files
> Training Enrollment
> Projecting
Open+Cvt+Cascade+ASEFEyes+Affine(width=128,height=128,x1=0.33,y1=0.45)+CvtFloat
> ...
> Training  "PCA"
> ...
[etc.]

**Comment by sklum** [comment]
IMO, there was some merit to this in terms of code correctness, but in the absense of a PR with the desired functionality, I'm going to close this ticket.
