### ISSUE TITLE
Reorganizing openbr/plugins

### ISSUE THREAD

**Issue by JordanCheney** [biometrics/openbr#329]
As OpenBR grows and adds more and more functionality it is becoming harder and harder to know what plugins are located where in 'openbr/plugins'.  Over the next few days I would like to start a project to reorganize the plugins folder. My initial thought on organization is to have modules within the plugins directory (initial thoughts would be core, i/o, gui, imgproc, etc...) and then have relevant plugins within these modules organized as 1 plugin per file. Searching for a specific plugin is then as simple as reading the file names. Thoughts?

**Comment by bklare** [comment]
A huge +1 from this guy.

**Comment by jklontz** [comment]
+1

**Comment by sklum** [comment]
Absolutely on board.  You might want to go through and cull/open up issues on duplicate plugins too.

**Comment by jklontz** [comment]
And obsolete plugins too.

**Comment by JordanCheney** [comment]
Any metric for what is obsolete?

**Comment by jklontz** [comment]
- EditTransform
- WordWiseTransform
- ColoredU2Transform
- SubtractBackgroundTransform
- RecursiveProductQuantizationDistance
- SentenceTransform
- SentenceSimilarityDistance
