### ISSUE TITLE
Error with cv::Mat

### ISSUE THREAD

**Issue by jarastrnad** [biometrics/openbr#330]
Hi, i testing openbr and

br::Template queryA("c:/1.jpg");
queryA >> *transform;

works fine.

But

cv::Mat img = cv::imread("c:/1.jpg");
br::Template queryA(img);
queryA >> *transform;

get error:
Failed to create gallery!
stream failed to open

**Comment by caotto** [comment]
This is a result of 1. the changes to stream (only expecting gallery input now), and 2. Transform::fromAlgorithm attaching a stream by default (so that projecting a templatelist is parallelized). I'm a little ambivalent on not doing 2 vs. reintroducing an in-memory project for stream

**Comment by caotto** [comment]
Addressed by c4ff790, we will just default it to false and avoid the issue.
