### ISSUE TITLE
C++_SDK function: compare(). return value bigger than 1 or less than 0

### ISSUE THREAD

**Issue by wowo200** [biometrics/openbr#338]
In the example: face_recognition.cpp line64, there is a comment : scores range from 0 to 1 and represent match probability.
But when I test this program, I got result somtimes  bigger than 1 or less than 0.
Is there any progress before using compare function?
How to avoid it?

**Comment by jklontz** [comment]
Can you post an example of the scores outside 0 to 1 range?

"Is there any progress before using compare function?
How to avoid it?"

I don't know what that means.

**Comment by jklontz** [comment]
Tracking in
https://github.com/biometrics/openbr/issues/338#issuecomment-76396461

Please don't double post.

**Comment by wowo200** [comment]
![a](https://cloud.githubusercontent.com/assets/10410486/6423851/5121dbbc-bf27-11e4-9c73-7fb169e94609.PNG)

I mean whether or not to preprocess the face photo.
When I compare the same photo always get score :7.14759.
My code command line is :  br -algorithm FaceRecognition -compare dir/1.bmp dir/1.bmp
My C++ code is same as the example "http://openbiometrics.org/doxygen/latest/group__cpp__plugin__sdk.html#cpp_face_recognition"  Face Recognition part.

**Comment by jklontz** [comment]
Ok I can confirm this on the master branch, which made me recall that we did in fact change the score normalization approach recently. The new approach is that 0 is the average non-match score, and 1 is the average match score, so match scores are now allowed to exceed this range.

Don't pre-process the face photo, the algorithm will do the preprocessing it needs.
