### ISSUE TITLE
Bug in SparseLDATransform

### ISSUE THREAD

**Issue by bklare** [biometrics/openbr#381]
As @jklontz noted, there is a bug with the use of `abs` in SpareLDATransform. This needs to be fixed and tested to see if the transform has value. 

https://github.com/biometrics/openbr/blob/a66017746fa66ee1ef6874166b7ad5f02e61b668/openbr/plugins/classification/lda.cpp#L617

**Comment by sklum** [comment]
Gunna close this due to inactivity.
