### ISSUE TITLE
Plot bug with bar charts

### ISSUE THREAD

**Issue by bklare** [biometrics/openbr#402]
One the TAR bar plots, the numbers printed for the second and third plots are wrong. It seems they are swapped (see screenshot). I would fix this but I think @bhklein can find and fix much faster. 

![image](https://cloud.githubusercontent.com/assets/982174/8826686/435b0cec-3056-11e5-9f3e-31bf733a2a37.png)

**Comment by bklare** [comment]
Here is a more prominent example: 

![image](https://cloud.githubusercontent.com/assets/982174/8826731/8518d0d8-3056-11e5-9eb5-646805bb46bc.png)

**Comment by bhklein** [comment]
Sorry about that, should be fixed with d4e42a035e0fc18a6e11a5cbf91b46258fd42d49

**Comment by bklare** [comment]
Thanks!
