### ISSUE TITLE
Unable to build openbr in Ubuntu

### ISSUE THREAD

**Issue by chanderbgoel** [biometrics/openbr#403]
a0393626@ubuntu:~/Work/Biometric_Recognition/openbr/build$ make
[  1%] Automoc for target stasm
[  1%] Built target stasm_automoc
[  2%] Building CXX object ../3rdparty/stasm4.0.0/build/CMakeFiles/stasm.dir/stasm/eyedet.cpp.o
In file included from /home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/stasm.h:58:0,
                 from /home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/eyedet.cpp:5:
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/misc.h:412:9: error: variable or field ‘OpenDetector’ declared void
     cv::CascadeClassifier& cascade,  // out
         ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/misc.h:412:5: error: ‘CascadeClassifier’ is not a member of ‘cv’
     cv::CascadeClassifier& cascade,  // out
     ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/misc.h:412:28: error: ‘cascade’ was not declared in this scope
     cv::CascadeClassifier& cascade,  // out
                            ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/misc.h:413:5: error: expected primary-expression before ‘const’
     const char*            filename, // in: basename.ext of cascade
     ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/misc.h:414:5: error: expected primary-expression before ‘const’
     const char*            datadir); // in
     ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/misc.h:418:9: error: ‘cv::CascadeClassifier’ has not been declared
     cv::CascadeClassifier* cascade,          // in
         ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/eyedet.cpp: In function ‘void stasm::DetectAllEyes(stasm::vec_Rect&, stasm::vec_Rect&, const Image&, stasm::EYAW, const Rect&, StasmCascadeClassifier)’:
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/eyedet.cpp:262:43: error: cannot convert ‘cv::CascadeClassifier*’ to ‘int*’ for argument ‘2’ to ‘stasm::vec_Rect stasm::Detect(const Image&, int*, const Rect*, double, int, int, int)’
                        facerect.width / 10);
                                           ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/eyedet.cpp:269:43: error: cannot convert ‘cv::CascadeClassifier*’ to ‘int*’ for argument ‘2’ to ‘stasm::vec_Rect stasm::Detect(const Image&, int*, const Rect*, double, int, int, int)’
                        facerect.width / 10);
                                           ^
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/eyedet.cpp: In function ‘void stasm::DetectAllMouths(stasm::vec_Rect&, const Image&, stasm::EYAW, const Rect&, int, int, const vec_Rect&, const vec_Rect&, cv::CascadeClassifier)’:
/home/a0393626/Work/Biometric_Recognition/openbr/3rdparty/stasm4.0.0/stasm/eyedet.cpp:293:35: error: cannot convert ‘cv::CascadeClassifier*’ to ‘int*’ for argument ‘2’ to ‘stasm::vec_Rect stasm::Detect(const Image&, int*, const Rect*, double, int, int, int)’
                facerect.width / 10);
                                   ^
make[2]: *** [../3rdparty/stasm4.0.0/build/CMakeFiles/stasm.dir/stasm/eyedet.cpp.o] Error 1
make[1]: *** [../3rdparty/stasm4.0.0/build/CMakeFiles/stasm.dir/all] Error 2
make: *** [all] Error 2
a0393626@ubuntu:~/Work/Biometric_Recognition/openbr/build$

**Comment by Cylix** [comment]
Exactly the same here, on macOS X 10.10.4.

**Comment by geoff-ellison** [comment]
Did anybody manage to solve this? If so, how?
Thx

**Comment by chanderbgoel** [comment]
I took an old version of opencv (2.4.9). This resolves the issue.

**Comment by geoff-ellison** [comment]
thanks @chanderbgoel! That did the trick.
I still can't get it working, build seems to have other issues (Qt-related) but that is a subject for another post.
