### ISSUE TITLE
Enrolling different queries with the same targets produces identical scores (within a Context)

### ISSUE THREAD

**Issue by imaus10** [biometrics/openbr#406]
If I run the following:

```
br_enroll("img1.jpg", "query.gal");
br_compare("target.gal", "query.gal", "out1.csv");
br_enroll("img2.jpg", "query.gal");
br_compare("target.gal", "query.gal", "out2.csv");
```

The scores are exactly the same in `out1.csv` and `out2.csv`. Looks like it's because `AlgorithmCore::compare` loads the gallery via `memGallery`:
https://github.com/biometrics/openbr/blob/6ad9e3fac54a8cac791d2a154fb0766a2b16c010/openbr/core/core.cpp#L449-L456
And `memGallery` only reads the file once:
https://github.com/biometrics/openbr/blob/6ad9e3fac54a8cac791d2a154fb0766a2b16c010/openbr/plugins/gallery/mem.cpp#L61-L65

While this is not necessarily a bug, it's based on the assumption that a gallery will not change over openbr's lifetime. But I think the above is a valid use. Is it necessary to cache the galleries in memory? Thoughts, workarounds? @jklontz

**Comment by jklontz** [comment]
Sorry, just getting back from vacation. Caching galleries in memory is useful for making multiple calls for `-compare` from the command line. The obvious workaround is to use a different file name for the second  gallery :)

**Comment by jklontz** [comment]
While it's not ideal, perhaps the easiest solution for now is to introduce a function to clear the memory gallery cache?

**Comment by sklum** [comment]
Going to punt on this until someone requests this functionality again.
