### ISSUE TITLE
-plot ERR bug

### ISSUE THREAD

**Issue by jklontz** [biometrics/openbr#413]
<img width="725" alt="screen shot 2015-08-14 at 9 23 43 am" src="https://cloud.githubusercontent.com/assets/682795/9274762/543a74e0-4266-11e5-95de-659372d6cc88.png">

@bhklein This has been around for a few weeks, just got around to reporting it.

**Comment by bhklein** [comment]
Sorry was out of town this weekend, should be fixed in 7f7c788e172d937e1031f1a00c0c31d387849ead

**Comment by jklontz** [comment]
Yup, thanks!
