### ISSUE TITLE
br command gives error

### ISSUE THREAD

**Issue by miller15** [biometrics/openbr#414]
After following installation instructions on openbiometrics.org, tested br in terminal on Mac and received following error.
cmake version: 2.8.12 (also tried with version 3.0.2)
Tried without success setting each RPATH and LD_LIBRARY_PATH to /usr/local/lib:/Users/m30039/Qt5.4.1/5.4/clang_64/lib

$ br
dyld: Library not loaded: @rpath/QtConcurrent.framework/Versions/5/QtConcurrent
  Referenced from: /usr/local/bin/br
  Reason: image not found
Trace/BPT trap: 5

**Comment by StevenSama** [comment]
mee too

**Comment by StevenSama** [comment]
dyld: Library not loaded: @rpath/QtConcurrent.framework/Versions/5/QtConcurrent
  Referenced from: /usr/local/bin/br
  Reason: image not found
Trace/BPT trap: 5
