### ISSUE TITLE
Broken links to documentation on http://openbiometrics.org/

### ISSUE THREAD

**Issue by bamos** [biometrics/openbr#415]
Under "Get Started", clicking on the algorithm (like "Face Recognition") links to a doxygen page with a 404: http://openbiometrics.org/doxygen/latest/group__cpp__plugin__sdk.html#cpp_face_recognition

**Comment by bklare** [comment]
Nice catch. We recently updated the docs and that link was not modified.
From the documentation link on the front page you can find the new docs at:
http://openbiometrics.org/docs/index.html

**Comment by bklare** [comment]
Fixed.
