### ISSUE TITLE
Tagged branches (v0.5.0) requires manual deletion of the `openbr-doc` submodule

### ISSUE THREAD

**Issue by bamos** [biometrics/openbr#417]
Hi, sorry for all the issues, but it could be helpful to explain in the `README` on the master branch and in other build locations that `.gitmodules` in previously tagged versions have an outdated `gitmodule` reference to `openbr-doc`. One solution is to remove the entry in `.gitmodules` and delete `share/openbr/doc`.

**Comment by jklontz** [comment]
This should no longer matter now that we are at 1.1
