### ISSUE TITLE
FaceRecognition ROC curves

### ISSUE THREAD

**Issue by bamos** [biometrics/openbr#418]
Hi, can you post the default face recognition ROC curves to this issue or add them to the website? I'm interested in seeing the performance on LFW.

**Comment by bklare** [comment]
Hi Brandon - at the end of this week we are releasing a new version of the
OpenBR algorihtm that will have improved accuracy. At that time we will
follow your good suggestion and check in a csv file corresponding to
accuracy on the LFW benchmark. We will also update the LFW script. This
will be in conjunction with a tutorial we are given at the IEEE BTAS
conference next week.

**Comment by bamos** [comment]
Thanks Brendan, excited to see the new ROC curve.

If anybody else is interested, here is the one from the current master branch: a890d39b9c4a21d851d3202b210ab41dfce2bfab

![image](https://cloud.githubusercontent.com/assets/707462/9586963/e336aeae-4fed-11e5-8a72-aae7b6522a54.png)
