### ISSUE TITLE
Load FaceRecognition Error

### ISSUE THREAD

**Issue by scdeng** [biometrics/openbr#420]
I built openbr on win8 64bit and ran face recognition sample as tutorial said. 

the command line is "br -algorithm FaceRecognition -compare D:/dog/code/openbr/data/MEDS/img/S354-01-t10_01.jpg D:/dog/code/openbr/data/MEDS/img/S354-02-t10_01.jpg -compare D:/dog/code/openbr/data/MEDS/img/S354-01-t10_01.jpg D:/dog/code/openbr/data/MEDS/img/S386-04-t10_01.jpg" 

the Expected command line output:
$ Set algorithm to FaceRecognition
$ Loading /usr/local/share/openbr/models/algorithms/FaceRecognition
$ Loading /usr/local/share/openbr/models/transforms//FaceRecognitionExtraction
$ Loading /usr/local/share/openbr/models/transforms//FaceRecognitionEmbedding
$ Loading /usr/local/share/openbr/models/transforms//FaceRecognitionQuantization
$ Comparing ../data/MEDS/img/S354-01-t10_01.jpg and ../data/MEDS/img/S354-02-t10_01.jpg
$ Enrolling ../data/MEDS/img/S354-01-t10_01.jpg to S354-01-t10_01r7Rv4W.mem
$ 100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
$ 100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
$ 1.8812
$ Comparing ../data/MEDS/img/S354-01-t10_01.jpg and ../data/MEDS/img/S386-04-t10_01.jpg
$ Enrolling ../data/MEDS/img/S354-01-t10_01.jpg to S354-01-t10_01r7Rv4W.mem
$ 100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
$ 100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
$ 0.571219

But I got these output
Set algorithm to FaceRecognition
Loading FaceRecognition
Warning: qUncompress: Z_DATA_ERROR: Input data is corrupted
  SDK Path: D:/dog/code/openbr/build-msvc2013/install
  File:
  Function:
  Line: 0
Fatal: Transform registry does not contain object named:
  SDK Path: D:/dog/code/openbr/build-msvc2013/install
  File:
  Function:
  Line: 0

I have model file at D:\dog\code\openbr\build-msvc2013\install\share\openbr\models\algorithms\FaceRecognition

How can I designate the br program to load FaceRecognition at proper location???

**Comment by jklontz** [comment]
Run `br` with a working directory `D:\dog\code\openbr\build-msvc2013\`. See `sdkPath` in http://openbiometrics.org/docs/api_docs/cpp_api/context/statics/#initialize for details.

**Comment by scdeng** [comment]
Hi @jklontz . Thanks for your reply. 

I ran the command above at directory D:\dog\code\openbr\build-msvc2013\ and D:\dog\code\openbr\build-msvc2013\install\, but the same error occured, the SDK path was D:/dog/code/openbr/build-msvc2013/install, in which there exists "share/openbr/openbr.bib". I think OpenBR found working directory properly.

I run "br" command only the output as follow:
OpenBR 0.5.0 Copyright (c) 2013 OpenBiometrics. All rights reserved.
Try running 'br -help'

I've stucked on this issue for a week, could you please do me a favor? THX

**Comment by esdebon** [comment]
run:

br -algorithm FaceRecognition image1.jpg image2.jpg
