### ISSUE TITLE
Install error on Version 1.0 

### ISSUE THREAD

**Issue by kumadam** [biometrics/openbr#424]
Hi, yesterday I saw it but there is no models.tar.gz right now.

File not found : http://github.com/biometrics/openbr/releases/download/v1.0.0/models.tar.gz

-- Configuring done
-- Generating done
-- Build files have been written to: /home/qwerty/Downloads/openbr/build
qwerty@qwerty-VirtualBox:~/Downloads/openbr/build$ make -j4
[  1%] [  1%] [  1%] [  2%] Automatic moc for target janus_create_templates
Automatic moc for target openbr
Automatic moc for target janus_create_gallery
Performing download step (download, verify and extract) for 'models'
[  2%] Built target janus_create_templates_automoc
[  2%] Built target janus_create_gallery_automoc
-- downloading...
     src='http://github.com/biometrics/openbr/releases/download/v1.0.0/models.tar.gz'
     dst='/home/qwerty/Downloads/openbr/build/models-prefix/src/models.tar.gz'
     timeout='none'
[  3%] [  3%] Automatic moc for target janus_evaluate_verify
Automatic moc for target janus_evaluate_search
[  3%] Built target janus_evaluate_verify_automoc
[  3%] Built target openbr_automoc
[  3%] Built target janus_evaluate_search_automoc
[  3%] Automatic moc for target janus_verify
[  3%] Automatic moc for target janus_verify_pairwise
[  4%] [  4%] Built target janus_verify_automoc
Automatic moc for target br
[  4%] Built target br_automoc
[  4%] [  4%] Automatic moc for target age_estimation
Built target janus_verify_pairwise_automoc
CMake Error at /home/qwerty/Downloads/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/qwerty/Downloads/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [0a7c79226d6629954aa32c835a1007b9]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [56;"Failure when receiving data from the peer"]

CMakeFiles/models.dir/build.make:82: recipe for target 'models-prefix/src/models-stamp/models-download' failed
make[2]: *** [models-prefix/src/models-stamp/models-download] Error 1
CMakeFiles/Makefile2:928: recipe for target 'CMakeFiles/models.dir/all' failed
make[1]: *** [CMakeFiles/models.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Built target age_estimation_automoc
[  4%] [  4%] Automatic moc for target face_recognition
Automatic moc for target face_recognition_evaluation
[  4%] Built target face_recognition_evaluation_automoc
[  4%] Built target face_recognition_automoc
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jklontz** [comment]
Should be fixed now!

**Comment by Justme21** [comment]
I have been having a similar problem as the one reported above: 

[  0%] CMake Error at /Users/jackgeary/Downloads/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/Users/jackgeary/Downloads/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [26cf71abd48cec8d7b2abf3e8f4ebfc4]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"unsupported protocol"]



[  0%] make[2]: *** [models-prefix/src/models-stamp/models-download] Error 1
make[1]: *** [CMakeFiles/models.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Automatic moc for target face_recognition
[  0%] Automatic moc for target face_recognition_evaluation
Automatic moc for target face_recognition_search
[  0%] Built target face_recognition_automoc
[  0%] [  0%] Built target face_recognition_evaluation_automoc
Built target face_recognition_search_automoc
make: *** [all] Error 2

I have looked about and have yet to find a solution that resolves the problem, though I have tried several times

**Comment by jklontz** [comment]
Hi can you try updating to 1.1.0?

**Comment by mfawcett** [comment]
I get the same error as Justme21 using 1.1.0

**Comment by jklontz** [comment]
I've seen the "unsupported protocol" issue before and was able to fix it by updating CMake

**Comment by mfawcett** [comment]
Updating to CMake 3.4.0 solved this. Note that the current instructions say to use CMake 3.0.2 which will fail against OpenBR 1.1.0

**Comment by StijnPil** [comment]
I tried it with both CMake 3.4.0 and 3.5.0 but still not working. 

`CMake Error at /Users/Stijn/Downloads/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/Users/Stijn/Downloads/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [26cf71abd48cec8d7b2abf3e8f4ebfc4]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"unsupported protocol"]



make[2]: *** [models-prefix/src/models-stamp/models-download] Error 1
make[1]: *** [CMakeFiles/models.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

**Comment by dyxu** [comment]
@jklontz  you can change the md5 to d41d8cd98f00b204e9800998ecf8427e in CMakeLists.txt at line 162 to solve it.

**Comment by pramodfaceR** [comment]
-- [download 100% complete]
CMake Error at /root/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/root/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [7c04357d80e7b4c8582a4dc8a08cdfbd]
        actual hash: [26cf71abd48cec8d7b2abf3e8f4ebfc4]

**Comment by pramodfaceR** [comment]
-- [download 99% complete]
-- [download 100% complete]
CMake Error at /root/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/root/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [7c04357d80e7b4c8582a4dc8a08cdfbd]
        actual hash: [26cf71abd48cec8d7b2abf3e8f4ebfc4]



make[2]: *** [models-prefix/src/models-stamp/models-download] Error 1
make[1]: *** [CMakeFiles/models.dir/all] Error 2
make: *** [all] Error 2
