### ISSUE TITLE
build error on the latest version

### ISSUE THREAD

**Issue by StevenSama** [biometrics/openbr#425]
Built target gender_estimation_automoc
CMake Error at /Users/Steven/work/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/Users/Steven/work/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [0a7c79226d6629954aa32c835a1007b9]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"unsupported protocol"]

make[2]: *** [models-prefix/src/models-stamp/models-download] Error 1
make[1]: *** [CMakeFiles/models.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Built target openbr
make: *** [all] Error 2

**Comment by jklontz** [comment]
Try updating to the latest cmake

**Comment by syoshio** [comment]
Yesterday (oct,7) I follow the instructions to install OpenBR, but I'm facing same problem... can you help me?

CMake Error at /home/sergio/Downloads/openbr/build/models-prefix/src/models-stamp/download-models.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/sergio/Downloads/openbr/build/models-prefix/src/models.tar.gz]
      expected hash: [22b158958907e08e611f11b1c62547c6]
        actual hash: [26cf71abd48cec8d7b2abf3e8f4ebfc4]

make[2]: ** [models-prefix/src/models-stamp/models-download] Erro 1
make[1]: ** [CMakeFiles/models.dir/all] Erro 2
make: ** [all] Erro 2

**Comment by koenokatachi** [comment]
Be sure to recheckout v1.1.0. Yesterday the tag was moved to another commit

**Comment by syoshio** [comment]
Thanks ! It worked!

**Comment by Justme21** [comment]
I am trying to install this as detailed on the site (http://openbiometrics.org/docs/install/), for mac, but I'm coming up with this error 

expected hash: [26cf71abd48cec8d7b2abf3e8f4ebfc4]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [1;"unsupported protocol"]

I am fairly certain it's version 1.1.0 I am using, and have updated cmake

**Comment by klugingenieria** [comment]
Hello guys, i have the same problem, i have installed openCV 3.1 and CMake 3.5:
mutante@mutante-Compaq-CQ45-Notebook-PC:~/Descargas/openbr/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake:224 (configure_file):
  configure_file called with unknown argument(s):

   COPY_ONLY

Call Stack (most recent call first):
  openbr/CMakeLists.txt:26 (qt5_add_resources)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mutante/Descargas/openbr/build
mutante@mutante-Compaq-CQ45-Notebook-PC:~/Descargas/openbr/build$ make -j4
[  0%] Automatic moc for target openbr
[  0%] Performing download step (download, verify and extract) for 'models'
[  0%] Automatic moc for target janus_evaluate_verify
[  0%] Automatic moc for target janus_verify
-- downloading...
     src='http://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz'
     dst='/home/mutante/Descargas/openbr/build/models-prefix/src/models.tar.gz'
     timeout='none'
[  0%] Built target janus_evaluate_verify_automoc
[  0%] Automatic moc for target janus_create_gallery
[  0%] Built target janus_verify_automoc
[  0%] Built target janus_create_gallery_automoc
[  0%] Automatic moc for target janus_create_templates
[  0%] Built target janus_create_templates_automoc
[  0%] Automatic moc for target janus_evaluate_search
[  0%] Automatic moc for target janus_verify_pairwise
[  0%] Built target janus_verify_pairwise_automoc
[  0%] Automatic moc for target br
[  0%] Built target janus_evaluate_search_automoc
[  0%] Automatic moc for target gender_estimation
[  0%] Built target br_automoc
CMake Error at /home/mutante/Descargas/openbr/build/models-prefix/src/models-stamp/download-models.cmake:27 (message):
  error: downloading
  'http://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log:   Trying 192.30.252.128...

  Connected to github.com (192.30.252.128) port 80 (#0)

  GET /biometrics/openbr/releases/download/v1.1.0/models.tar.gz HTTP/1.1

  Host: github.com

  User-Agent: curl/7.44.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-length: 0

  Location:
  https://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz


  Connection: close

  

  Closing connection 0

  Issue another request to this URL:
  'https://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz'


  Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  



make[2]: *** [models-prefix/src/models-stamp/models-download] Error 1
make[1]: *** [CMakeFiles/models.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[  0%] Built target gender_estimation_automoc
[  0%] Automatic moc for target face_recognition_train
[  0%] Built target face_recognition_train_automoc
[  0%] Built target openbr_automoc
make: *** [all] Error 2
mutante@mutante-Compaq-CQ45-Notebook-PC:~/Descargas/openbr/build$ 

pls help me, i have changed configuration files according to: 
https://github.com/biometrics/openbr/commit/16a3b3a7dc4dc12bb9e359d8ba9b2edf9adc471d

thanks in advance

**Comment by Boukary** [comment]
Problem solved

download manually the models tar file from https://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz

and put it in this directory
build/models-prefix/src

run the make -j4 command, it will work now
