### ISSUE TITLE
segfault on LDA(768) step of training FaceRecognition

### ISSUE THREAD

**Issue by koenokatachi** [biometrics/openbr#428]
so i take the full string describing the predefined FaceRecognition algorithm and train the algo over the BioID image set

```bash
ALG="FR_Detect+(FR_Eyes+FR_Represent)/(FR_Eyebrows+FR_Represent)/(FR_Mouth+FR_Represent)/(FR_Nose+FR_Represent)/(FR_Face+FR_Represent+ScaleMat(2.0))+Cat+LDA(768)+Normalize(L2):Dist(L2)"

bin/br -algorithm "$ALG" -train ../data-from-build-test/BioID/img Eigenfaces
```

output:
```
(( much stuff here ))
...
Training "LDA(pcaKeep=768)" 
... 
./1.sh: line 6: 24785 Segmentation fault      bin/br -algorithm "$ALG" -train ../data-from-build-test/BioID/img Eigenfaces
```

here is the full run log https://gist.githubusercontent.com/koenokatachi/f51c524845ff4d71cbdd/raw/1be2060726bf4a340b3c776902e583dadba08ee0/run.log

i tried to use a directory with less images (500, 100, 10). all the same

build: master

8gb ram, 4x intel x64, ubuntu 12.04

**Comment by jklontz** [comment]
LDA requires labeled training data. BioID is not labeled with subject
identities. Note how in LFW each subject has his/her own folder of images:
http://vis-www.cs.umass.edu/lfw/lfw.tgz
