### ISSUE TITLE
commit 9633db66d3958cbc5607a59904c49f81676619a1 is pointless

### ISSUE THREAD

**Issue by koenokatachi** [biometrics/openbr#429]
replacing Dist(L2) with Unit(Dist(L2)) is pointless because Unit(Dist) is equivalent to Dist for any Dist (defaults in UnitDistance class: a=1,b=0)

So FaceRecognition_1_1 is literally the same as FaceRecognition_1_0

**Comment by jklontz** [comment]
We aren't done fixing #426, be patient.

**Comment by bklare** [comment]
`a` and `b` are learned during train time and serialized via Q_PROPERTY.
For version 1.1 the learned model values are:
a=27.158
b=-0.88102

**Comment by koenokatachi** [comment]
Thanks for the responses.

I dont understand why cant it be simple? Last step of FaceRecognition's representation algo is Normalize(L2). So the input to Dist(L2) (when comparing) are two "things" of unit length in L2. So the comparing result for any two "things" gonna be in [0,2] no matter what (assuming Dist applies -ln(1+x) to the result by default it is gonna be [-1.1,0]). Am I wrong?
