### ISSUE TITLE
FaceRecognition compare result to percentage?

### ISSUE THREAD

**Issue by marcbackes** [biometrics/openbr#430]
Hi!

For a project I am currently working on, I need face recognition of two face and show the percentage of probability that it's a match.

I use the following command:
br -algorithm FaceRecognition -compare face1.png face2.png

The output result comes as NegativeLogPlusOne as far as I understand. I am not really a math genius and I would need help to convert the result to a percentage value. Can anybody help?

Thanks!
Marc

**Comment by koenokatachi** [comment]
y = -ln(1+x) => x = exp(-y)-1

**Comment by koenokatachi** [comment]
I'd love to see the ```-compare``` output as a [0,1] number as well. Not what we get right now

**Comment by kashyap2690** [comment]
To get values normalized to [0,1]  it is required to store values of min, max, mean, stddev for both genuine and impostor while training FaceRecognition algorithm provided in models.

With current release v1.1.0, the FaceRecognition algorithm uses Unit Distance which has only mean value for both.
The training need to be performed with MatchProbability distance.

Waiting for a trained FaceRecognition algorithm models with MatchProbabilty distance, which will give normalized score in [0.1].

**Comment by jklontz** [comment]
I'm closing this issue as "won't fix". Returning match probability is inherently difficult as it is very data quality dependent. If you need a match probability, you're best off measuring accuracy on your own dataset.

**Comment by kashyap2690** [comment]
Right, but isn't current one Unit distance also data quality dependent?
I mean it uses genuineMean and impostorMean of data provided while training.

**Comment by jklontz** [comment]
It certainly is :)

**Comment by kashyap2690** [comment]
I would say we should at least respect Globals->scoreNormalization flag.
