### ISSUE TITLE
What does the result of FaceRecognition mean?

### ISSUE THREAD

**Issue by notheory** [biometrics/openbr#436]
I'm a newer of face recognition. I am confused about the meaning of the result of "br -algorithm -compare". I know it will always output a double-type value. It seems that larger value means more similar... But what does it mean?

**Comment by jklontz** [comment]
Results are normalized against the training set such that a score of 0 represents the average non-match score and a score of 1 represents the average match score.

**Comment by notheory** [comment]
Do we need normalize it by ourselves? I got result like 2.61145

**Comment by notheory** [comment]
And what does the percentage mean when compare two pictures? Sometimes the percentage value is not 100.00%, or even 0.00%.

**Comment by jklontz** [comment]
Similarities are still allowed to fall outside the 0 to 1 range. So a value greater than 1 would indicate similarity greater than the average match from the training set.

**Comment by notheory** [comment]
When i use the "br -algorithm -compare" and "br -algorithm -enrollAll -enroll" command, sometimes i got the result like "92.45% ELAPSED=00:00:01 REMAINING=00:00:00 COUNT=15". What does the 92.45% mean? Sometimes even got result with 0.00%. Thanks!

**Comment by jklontz** [comment]
oh that's just a progress bar :)

**Comment by notheory** [comment]
Does a result of "-3.40282e+38" means "very different" or not available? And some other results of "-inf"?

**Comment by jklontz** [comment]
Means not available because face detection failed in one or both of the images

**Comment by iamraphson** [comment]
Hello @jklontz 

I'm new to OpenBr. Please can you help me intercept the following result,

`Set algorithm to FaceRecognition
Loading /usr/local/share/openbr/models/algorithms/FaceRecognition
Comparing 3502724.jpeg and T3J2E0ML5-U3J2KG32Q-421e614b5d8f-1024.jpeg
Enrolling 3502724.jpeg to 3502724wYiAun.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
0.200711`

`Set algorithm to FaceRecognition
Loading /usr/local/share/openbr/models/algorithms/FaceRecognition
Comparing 16465067_1627912544184753_7001777723139948544_n.jpg and cc.jpg
Enrolling 16465067_1627912544184753_7001777723139948544_n.jpg to 16465067_1627912544184753_7001777723139948544_nmzSxDx.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
0.165308`

`Set algorithm to FaceRecognition
Loading /usr/local/share/openbr/models/algorithms/FaceRecognition
Comparing 3502724.jpeg and T3J2E0ML5-U3J2KG32Q-421e614b5d8f-1024.jpeg
Enrolling 3502724.jpeg to 3502724wYiAun.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
0.200711`

`Set algorithm to FaceRecognition
Loading /usr/local/share/openbr/models/algorithms/FaceRecognition
Comparing 3502724.jpeg and 3502724.jpeg
Enrolling 3502724.jpeg to 3502724wYiAun.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
23.9268`

Thanks
