### ISSUE TITLE
Permission denied on push

### ISSUE THREAD

**Issue by miller15** [biometrics/openbr#438]
I have created a new branch, added the file I created to that branch, and committed, however I am unable to push. Error can be seen in the screenshot. GitHub has a couple help topics on this, however the first one was unable to help me. https://help.github.com/articles/error-permission-to-user-repo-denied-to-user-other-repo/

*The second one would need to be explored by the openbr repo owner.
https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user/

![image](https://cloud.githubusercontent.com/assets/8574097/10770593/849db3cc-7cc2-11e5-96ab-09be0fce0d86.png)

**Comment by jklontz** [comment]
Hi, you should fork the repository and send a pull request!
