### ISSUE TITLE
Build Faild : IlmImf

### ISSUE THREAD

**Issue by Orgenus** [biometrics/openbr#445]
[ 32%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfWav.cpp.o
[ 32%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfIntAttribute.cpp.o
[ 32%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfKeyCode.cpp.o
[ 32%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfFloatAttribute.cpp.o
Linking CXX static library ../lib/libIlmImf.a
[ 32%] Built target IlmImf
make: *** [all] Error 2

**Comment by jklontz** [comment]
This seems like an OpenCV build error?

**Comment by Orgenus** [comment]
Yes. http://openbiometrics.org/docs/install/#linux step 3. make -j4 error.
