### ISSUE TITLE
 face recognition failed

### ISSUE THREAD

**Issue by shi19871987** [biometrics/openbr#446]
hi,
 i followed  the constructions in http://openbiometrics.org/docs/install/.  when I "make test",face recognition module failed. the reason I think is "Warning: QIODevice::read: device not open" in the log. How can i fixed it. qt version is Qt Creator 3.5.0 based on Qt 5.4.2.V15.10 ubuntu.

test log is:
Start testing: Nov 12 17:24 CST
----------------------------------------------------------
1/7 Testing: br_initialize
1/7 Test: br_initialize
Command: "/home/jackie/openbr/build/app/br/br"
Directory: /home/jackie/openbr
"br_initialize" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
OpenBR 1.1.0 Copyright (c) 2013 OpenBiometrics. All rights reserved.
Try running 'br -help'
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Passed.
"br_initialize" end time: Nov 12 17:24 CST
"br_initialize" time elapsed: 00:00:00
----------------------------------------------------------

2/7 Testing: face_recognition_search_test
2/7 Test: face_recognition_search_test
Command: "/home/jackie/openbr/build/app/examples/face_recognition_search"
Directory: /home/jackie/openbr/build
"face_recognition_search_test" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
Loading /home/jackie/openbr/share/openbr/models/algorithms/FaceRecognition
Warning: QIODevice::read: device not open
  SDK Path: /home/jackie/openbr
  File: 
  Function: 
  Line: 0
Fatal: miss read
  SDK Path: /home/jackie/openbr
  File: 
  Function: 
  Line: 0
<end of output>
Test time =   0.31 sec
----------------------------------------------------------
Test Failed.
"face_recognition_search_test" end time: Nov 12 17:24 CST
"face_recognition_search_test" time elapsed: 00:00:00
----------------------------------------------------------

3/7 Testing: face_recognition_train_test
3/7 Test: face_recognition_train_test
Command: "/home/jackie/openbr/build/app/examples/face_recognition_train"
Directory: /home/jackie/openbr/build
"face_recognition_train_test" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
<end of output>
Test time =   0.19 sec
----------------------------------------------------------
Test Passed.
"face_recognition_train_test" end time: Nov 12 17:24 CST
"face_recognition_train_test" time elapsed: 00:00:00
----------------------------------------------------------

4/7 Testing: age_estimation_test
4/7 Test: age_estimation_test
Command: "/home/jackie/openbr/build/app/examples/age_estimation"
Directory: /home/jackie/openbr/build
"age_estimation_test" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
Loading /home/jackie/openbr/share/openbr/models/algorithms/AgeRegression
Loading /home/jackie/openbr/share/openbr/models/transforms/FaceClassificationExtraction
Loading /home/jackie/openbr/share/openbr/models/transforms/AgeRegressor
Called Expand project(Template,Template), nothing will happen
Called Expand project(Template,Template), nothing will happen
Called Expand project(Template,Template), nothing will happen
Called Expand project(Template,Template), nothing will happen
S354-01-t10_01.jpg age: 32
S001-01-t10_01.jpg age: 26
<end of output>
Test time =   3.57 sec
----------------------------------------------------------
Test Passed.
"age_estimation_test" end time: Nov 12 17:24 CST
"age_estimation_test" time elapsed: 00:00:03
----------------------------------------------------------

5/7 Testing: face_recognition_evaluation_test
5/7 Test: face_recognition_evaluation_test
Command: "/home/jackie/openbr/build/app/examples/face_recognition_evaluation"
Directory: /home/jackie/openbr/build
"face_recognition_evaluation_test" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
Set algorithm to FaceRecognition
Set path to ../data/MEDS/img/
Loading /home/jackie/openbr/share/openbr/models/algorithms/FaceRecognition
Warning: QIODevice::read: device not open
  SDK Path: /home/jackie/openbr
  File: 
  Function: 
  Line: 0
Fatal: miss read
  SDK Path: /home/jackie/openbr
  File: 
  Function: 
  Line: 0
<end of output>
Test time =   0.15 sec
----------------------------------------------------------
Test Failed.
"face_recognition_evaluation_test" end time: Nov 12 17:24 CST
"face_recognition_evaluation_test" time elapsed: 00:00:00
----------------------------------------------------------

6/7 Testing: gender_estimation_test
6/7 Test: gender_estimation_test
Command: "/home/jackie/openbr/build/app/examples/gender_estimation"
Directory: /home/jackie/openbr/build
"gender_estimation_test" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
Loading /home/jackie/openbr/share/openbr/models/algorithms/GenderClassification
Loading /home/jackie/openbr/share/openbr/models/transforms/FaceClassificationExtraction
Loading /home/jackie/openbr/share/openbr/models/transforms/GenderClassifier
Called Expand project(Template,Template), nothing will happen
Called Expand project(Template,Template), nothing will happen
Called Expand project(Template,Template), nothing will happen
Called Expand project(Template,Template), nothing will happen
S354-01-t10_01.jpg gender: Male
S001-01-t10_01.jpg gender: Female
<end of output>
Test time =   3.92 sec
----------------------------------------------------------
Test Passed.
"gender_estimation_test" end time: Nov 12 17:24 CST
"gender_estimation_test" time elapsed: 00:00:03
----------------------------------------------------------

7/7 Testing: face_recognition_test
7/7 Test: face_recognition_test
Command: "/home/jackie/openbr/build/app/examples/face_recognition"
Directory: /home/jackie/openbr/build
"face_recognition_test" start time: Nov 12 17:24 CST
Output:
----------------------------------------------------------
Loading /home/jackie/openbr/share/openbr/models/algorithms/FaceRecognition
Warning: QIODevice::read: device not open
  SDK Path: /home/jackie/openbr
  File: 
  Function: 
  Line: 0
Fatal: miss read
  SDK Path: /home/jackie/openbr
  File: 
  Function: 
  Line: 0
<end of output>
Test time =   0.32 sec
----------------------------------------------------------
Test Failed.
"face_recognition_test" end time: Nov 12 17:24 CST
"face_recognition_test" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Nov 12 17:24 CST

**Comment by jklontz** [comment]
Does running `openbr/scripts/downloadMEDS.sh` first fix it?

**Comment by shi19871987** [comment]
of course I did it. I have fixed yet through checking the code and modifying it. Thanks a lot.
