### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Orgenus** [biometrics/openbr#448]
/root/openbr/openbr/core/opencvutils.h:57:20: error: 'CvStatModel' was not declared in this scope
/root/openbr/openbr/core/opencvutils.h:57:33: error: 'model' was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                 ^
/root/openbr/openbr/core/opencvutils.h:57:52: error: expected primary-expression before '&' token
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                    ^
/root/openbr/openbr/core/opencvutils.h:57:53: error: 'stream' was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                     ^
make[2]: *** [openbr/CMakeFiles/openbr.dir/openbr_plugin.cpp.o] Error 1
make[1]: *** [openbr/CMakeFiles/openbr.dir/all] Error 2
make: *** [all] Error 2

**Comment by jklontz** [comment]
I'm closing this issue as there isn't remotely enough information included assist.
