### ISSUE TITLE
seg fault on br_get_filename from Python

### ISSUE THREAD

**Issue by mfawcett** [biometrics/openbr#452]
The following Python code produces a Seg fault on the br_get_filename line:

```
imgbuffer = open(image, 'rb').read()
template = br.br_load_img(imgbuffer, len(imgbuffer))
br.br_set_filename(template, os.path.basename(image))
filename = br.br_get_filename(template)
```

**Comment by sklum** [comment]
We don't have anyone specifically working on the python wrappers at this time.  We'd welcome a PR with a fix if this is still an issue!
