### ISSUE TITLE
Plotting broken in latest version of R/ggplot2

### ISSUE THREAD

**Issue by jklontz** [biometrics/openbr#453]
```
$ br -plot Algorithm_Dataset/ROCFR_LFW.csv results.pdf 
Plotting 1 file(s) to results.pdf
Failed to run 'Rscript', did you forget to install R?  See online documentation of 'br_plot' for required R packages.  Otherwise, try running Rscript on ./results.R to get the exact error.
Joshs-MacBook-Pro:FaceRecognition jklontz$ Rscript results.R 

Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
Don't know how to automatically pick scale for object of type AsIs. Defaulting to continuous
Error: Aesthetics must be either length 1 or the same as the data (500): colour, linetype, size, x, y
Execution halted
```

@bhklein FYI. Time permitting, I'll try to tackle it tomorrow.

**Comment by jklontz** [comment]
The issue was that I have version 2.0.0 of ggplot2 installed which evidently includes some breaking changes :) As a workaround I downgraded to 1.0.1.

The main issue seems to be the use of the if-else ternary operator in plotLine where the `else` condition is `NULL`:
`p <- qplot(X, if(flipY) 1-Y else Y, data=lineData, main=options$title, geom=geometry, size=I(if("size" %in% names(options)) as.numeric(options$size) else .5), colour=if(majorSize > 1) factor(eval(parse(text=majorHeader))) else NULL, linetype=if(minorSize > 1) factor(eval(parse(text=minorHeader))) else NULL, xlab=options$xTitle, ylab=options$yTitle) + theme_minimal()`

That syntax seems no longer supported. Not sure what the fix is for us.

**Comment by bhklein** [comment]
K I'll take a look at it this week.

**Comment by hanglstanf** [comment]
Got the similar issue when trying to run 
br -algorithm FaceRecognition -path ../data/MEDS/img/ \
-enroll ../data/MEDS/sigset/MEDS_frontal_target.xml target.gal \
-enroll ../data/MEDS/sigset/MEDS_frontal_query.xml query.gal \
-compare target.gal query.gal scores.mtx \
-makeMask ../data/MEDS/sigset/MEDS_frontal_target.xml ../data/MEDS/sigset/MEDS_frontal_query.xml MEDS.mask \
-eval scores.mtx MEDS.mask Algorithm_Dataset/FaceRecognition_MEDS.csv \
-plot Algorithm_Dataset/FaceRecognition_MEDS.csv MEDS

**Comment by hrbrmstr** [comment]
It looks like this is [still an issue](http://stackoverflow.com/questions/39135479/plotting-broken-in-latest-version-of-r-ggplot2) for some folks. Folks can follow [this example](http://stackoverflow.com/a/17082609/1457051) to install an older version of ggplot2.

**Comment by hanglstanf** [comment]
@hrbrmstr  I have successfully installed ggplot2 using your method. However, I still got the following result:
`Attaching package: ‘gplots’

The following object is masked from ‘package:stats’:

    lowess

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
$mar
[1] 1.1 1.1 4.1 1.1

$xpd
[1] FALSE

$cex
[1] 0.66

NULL
NULL
The following `from` values were not present in `x`: col, color, pch, cex, lty, lwd, srt, adj, bg, fg, min, max
The following `from` values were not present in `x`: col, color, pch, cex, lty, lwd, srt, adj, bg, fg, min, max
The following `from` values were not present in `x`: col, color, pch, cex, lty, lwd, srt, adj, bg, fg, min, max
The following `from` values were not present in `x`: col, color, pch, cex, lty, lwd, srt, adj, bg, fg, min, max
The following `from` values were not present in `x`: col, color, pch, cex, lty, lwd, srt, adj, bg, fg, min, max
Error in plotLine(lineData = DET, options = list(xLog = TRUE, xTitle = "False Accept Rate",  : 
  could not find function "theme_minimal"
Execution halted
lihangdeMacBook-Pro:scripts lihang$ `

**Comment by hanglstanf** [comment]
Finally tackled this problem!  Thanks guys!

**Comment by sklum** [comment]
Closing this as it seems to be fixed (or a workaround is in place).
