### ISSUE TITLE
I can‘t download the files which in release

### ISSUE THREAD

**Issue by KiraWesker** [biometrics/openbr#455]
`error: downloading
  'http://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz'
  failed

    status_code: 56
    status_string: "Failure when receiving data from the peer"
    log: Hostname was NOT found in DNS cache
    Trying 192.30.252.129...

  Connected to github.com (192.30.252.129) port 80 (#0)

  GET /biometrics/openbr/releases/download/v1.1.0/models.tar.gz HTTP/1.1

  User-Agent: curl/7.38.0

  Host: github.com

  Accept: */*

  

  Recv failure: Connection reset by peer

  Closing connection 0`

So may you give me an another way to download it

**Comment by bhklein** [comment]
Hi,
Looks like you're using `curl`, try

`curl -kLO https://github.com/biometrics/openbr/releases/download/v1.1.0/models.tar.gz models.tar.gz`

or download it under the [1.1.0 release](https://github.com/biometrics/openbr/releases)

Thanks!
