### ISSUE TITLE
i can't download the models.tar.gz(v1.1.0),who can send me?thank you very much.

### ISSUE THREAD

**Issue by LiYX** [biometrics/openbr#458]
493234798@qq.com,thank you very much.

**Comment by soenter** [comment]
被“墙”了，通过代理下吧

**Comment by dyxu** [comment]
现在还需要吗？

**Comment by AlexisTM** [comment]
https://github.com/biometrics/openbr/releases

Models.tar.gz is in the release, you can download it below "1.1.0" version

**Comment by sklum** [comment]
Closing this.

**Comment by qintxwd** [comment]
jsqinyinghao@live.com  ,i need too.thanks
