### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by DuyguA** [biometrics/openbr#459]
Hello,

I'm following Unix installation, I'm on Ubuntu 14.04. 
cmake -DCMAKE_BUILD_TYPE=Release .. is succseful but , make fails with:

[  2%] [  3%] [  3%] Built target models
[  4%] Automoc for target janus_create_templates
Automoc for target openbr
Automoc for target janus_create_gallery
[  4%] Automoc for target janus_evaluate_search
[  4%] [  4%] [  4%] Built target janus_create_gallery_automoc
Built target janus_create_templates_automoc
Built target janus_evaluate_search_automoc
[  5%] [  5%] [  5%] Automoc for target janus_verify_pairwise
Automoc for target janus_evaluate_verify
Automoc for target janus_verify
[  5%] Built target janus_verify_pairwise_automoc
[  5%] Built target janus_evaluate_verify_automoc
[  5%] Built target janus_verify_automoc
[  6%] Automoc for target br
[  6%] [  6%] Automoc for target face_recognition
Automoc for target age_estimation
[  6%] [  6%] Built target br_automoc
Built target age_estimation_automoc
[  6%] [  6%] Built target face_recognition_automoc
Automoc for target face_recognition_evaluation
[  7%] [  7%] Automoc for target face_recognition_search
[  7%] [  7%] Automoc for target face_recognition_train
Built target openbr_automoc
Built target face_recognition_evaluation_automoc
[  7%] Built target face_recognition_search_automoc
[  7%] [  7%] Built target face_recognition_train_automoc
[  7%] Automoc for target gender_estimation
Automoc for target br-gui
[  7%] [  7%] Built target br-gui_automoc
Built target gender_estimation_automoc
[  7%] [  7%] [  7%] [  7%] Building CXX object openbr/CMakeFiles/openbr.dir/core/eval.cpp.o
Building CXX object openbr/CMakeFiles/openbr.dir/openbr_plugin.cpp.o
Building CXX object openbr/CMakeFiles/openbr.dir/core/opencvutils.cpp.o
Building CXX object openbr/CMakeFiles/openbr.dir/core/core.cpp.o
In file included from /home/duygualtinok/openbr/openbr/core/eval.cpp:21:0:
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:55:27: error: ‘CvStatModel’ does not name a type
     void storeModel(const CvStatModel &model, QDataStream &stream);
                           ^
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:55:40: error: ISO C++ forbids declaration of ‘model’ with no type [-fpermissive]
     void storeModel(const CvStatModel &model, QDataStream &stream);
                                        ^
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:57:20: error: variable or field ‘loadModel’ declared void
     void loadModel(CvStatModel &model, QDataStream &stream);
                    ^
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:57:20: error: ‘CvStatModel’ was not declared in this scope
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:57:33: error: ‘model’ was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                 ^
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:57:52: error: expected primary-expression before ‘&’ token
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                    ^
/home/duygualtinok/openbr/./openbr/core/opencvutils.h:57:53: error: ‘stream’ was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                     ^
In file included from /home/duygualtinok/openbr/openbr/core/opencvutils.cpp:23:0:
/home/duygualtinok/openbr/openbr/core/opencvutils.h:55:27: error: ‘CvStatModel’ does not name a type
     void storeModel(const CvStatModel &model, QDataStream &stream);
                           ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:55:40: error: ISO C++ forbids declaration of ‘model’ with no type [-fpermissive]
     void storeModel(const CvStatModel &model, QDataStream &stream);
                                        ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:20: error: variable or field ‘loadModel’ declared void
     void loadModel(CvStatModel &model, QDataStream &stream);
                    ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:20: error: ‘CvStatModel’ was not declared in this scope
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:33: error: ‘model’ was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                 ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:52: error: expected primary-expression before ‘&’ token
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                    ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:53: error: ‘stream’ was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                     ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:266:36: error: ‘CvStatModel’ does not name a type
 void OpenCVUtils::storeModel(const CvStatModel &model, QDataStream &stream)
                                    ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:266:49: error: ISO C++ forbids declaration of ‘model’ with no type [-fpermissive]
 void OpenCVUtils::storeModel(const CvStatModel &model, QDataStream &stream)
                                                 ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp: In function ‘void OpenCVUtils::storeModel(const int&, QDataStream&)’:
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:274:11: error: request for member ‘save’ in ‘model’, which is of non-class type ‘const int’
     model.save(qPrintable(tempFile.fileName()));
           ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp: At global scope:
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:302:29: error: variable or field ‘loadModel’ declared void
 void OpenCVUtils::loadModel(CvStatModel &model, QDataStream &stream)
                             ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:302:29: error: ‘CvStatModel’ was not declared in this scope
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:302:42: error: ‘model’ was not declared in this scope
 void OpenCVUtils::loadModel(CvStatModel &model, QDataStream &stream)
                                          ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:302:61: error: expected primary-expression before ‘&’ token
 void OpenCVUtils::loadModel(CvStatModel &model, QDataStream &stream)
                                                             ^
/home/duygualtinok/openbr/openbr/core/opencvutils.cpp:302:62: error: ‘stream’ was not declared in this scope
 void OpenCVUtils::loadModel(CvStatModel &model, QDataStream &stream)
                                                              ^
make[2]: **\* [openbr/CMakeFiles/openbr.dir/core/opencvutils.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
In file included from /home/duygualtinok/openbr/openbr/openbr_plugin.cpp:42:0:
/home/duygualtinok/openbr/openbr/core/opencvutils.h:55:27: error: ‘CvStatModel’ does not name a type
     void storeModel(const CvStatModel &model, QDataStream &stream);
                           ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:55:40: error: ISO C++ forbids declaration of ‘model’ with no type [-fpermissive]
     void storeModel(const CvStatModel &model, QDataStream &stream);
                                        ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:20: error: variable or field ‘loadModel’ declared void
     void loadModel(CvStatModel &model, QDataStream &stream);
                    ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:20: error: ‘CvStatModel’ was not declared in this scope
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:33: error: ‘model’ was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                 ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:52: error: expected primary-expression before ‘&’ token
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                    ^
/home/duygualtinok/openbr/openbr/core/opencvutils.h:57:53: error: ‘stream’ was not declared in this scope
     void loadModel(CvStatModel &model, QDataStream &stream);
                                                     ^
make[2]: **\* [openbr/CMakeFiles/openbr.dir/core/eval.cpp.o] Error 1
make[2]: **\* [openbr/CMakeFiles/openbr.dir/openbr_plugin.cpp.o] Error 1
make[1]: **\* [openbr/CMakeFiles/openbr.dir/all] Error 2
make: **\* [all] Error 2

I have OpenCV and OpenCV contrib, I used them many times. Can anybody help? Thanx in advance.

**Comment by sklum** [comment]
@DuyguA What version of OpenCV are you linking against?

**Comment by adisis** [comment]
I also got similar error, I using opencv 3.1.0

**Comment by adisis** [comment]
for opencv 3.x replace cvStatModel with cv::ml::StatModel
and impact to 
core/opencvutils.h:55
core/opencvutils.h:57
core/opencvutils.cpp:266
core/opencvutils.cpp:302

but I still got error on openbr/core/opencvutils.cpp:316: error: no matching function for call to 'cv::ml::StatModel::load(const char*)'
     model.load(qPrintable(tempFile.fileName()));

**Comment by sklum** [comment]
We do not support compiling with OpenCV 3.* at the moment, but hope to soon.
