### ISSUE TITLE
Segmentation fault in openbr

### ISSUE THREAD

**Issue by Boukary** [biometrics/openbr#460]
I've  installed openbr in ubuntu 14.04 as dual boot , it works perfectly 
when i tried to install it in ubuntu 14.04 as a virtuel machine in VMware , cmake gives me no error , but 
when i run br command line it gives me :

root@ubuntu:/usr/local/openbr/build# br
Segmentation fault (core dumped)

any suggest ??

**Comment by sklum** [comment]
@Boukary It's hard to help without a little more info.  `br` works fine on my machine and AFAIK it's still functional on Ubuntu.  Can you build in debug mode and provide a stack trace?

**Comment by Boukary** [comment]
thnks a lot Mr sklum , it's solved :p
