### ISSUE TITLE
problem with hack the openbr

### ISSUE THREAD

**Issue by mohamaddanesh** [biometrics/openbr#463]
Hi,
In hack guidance for linux it says 
Browse to your pre-existing build directory "openbr/build" then select "Next". Select "Run CMake" then "Finish".
How should I browse to openbr/build? with file explorer? and where is the "Next" button? How to "Run CMake"?
Thanks.

**Comment by sklum** [comment]
@mohamaddanesh Those instructions are relevant when using [Qt Creator](http://www.qt.io/ide/).

Note step one in that section:
```
1.  Open Qt Creator IDE

$ qtcreator &
```

**Comment by DetionDX** [comment]
same problem
