### ISSUE TITLE
face recognition always return zero

### ISSUE THREAD

**Issue by omerfarukz** [biometrics/openbr#465]
Hi,
Installed openbr to macos as described on installation document. Just tried following commands in terminal and result is below. Tried some other images and tried to same image instead of two different image but result is always 0(zero). 

Omers-MacBook-Pro:Desktop omr$ br -algorithm FaceRecognition -compare me.jpg me.jpg
Set algorithm to FaceRecognition
Comparing me.jpg and me.jpg
Enrolling me.jpg to me1a22rV.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
0

**Comment by sklum** [comment]
@omerfarukz What are the results when you enroll the same data we provide at `openbr/test/family.jpg`?  When I run things, I get:

```
Set algorithm to FaceRecognition
Loading /usr/local/share/openbr/models/algorithms/FaceRecognition
Comparing family.jpg and family.jpg
Enrolling family.jpg to familyzKbIoC.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
23.9268
```

One thing worth noting is that there is no output for loading the `FaceRecognition` model.  Can you verify that you indeed have the models (installed to `share/openbr/models`)?

**Comment by sklum** [comment]
Closing this as it seems to be resolved?

**Comment by omerfarukz** [comment]
Tried family.jpg as you described. Output is below.

omrs-Mac-Pro:Desktop omr$ br -algorithm FaceRecognition -compare family.jpg family.jpg
Set algorithm to FaceRecognition
Comparing family.jpg and family.jpg
Enrolling family.jpg to familyzKbIoC.mem
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
100.00%  ELAPSED=00:00:00  REMAINING=00:00:00  COUNT=1
0

**Comment by sklum** [comment]
There still isn't output for loading the model:
`Loading /usr/local/share/openbr/models/algorithms/FaceRecognition`

This makes me think it's defaulting to the untrained abbreviation.  Again, I'd check that you actually have the model.
