### ISSUE TITLE
openframeworks

### ISSUE THREAD

**Issue by antimodular** [biometrics/openbr#466]
openBR looks super interesting.

do you think it is possible to make a Qt independent version that would allow www.openframeworks.cc to use openBR? 

openframeworks.cc already has a static opencv.a version for example and other face trackers.
from your graphic it seems openBR ties directly in to Qt and opencv.

thanks for any pointers.
stephan

**Comment by jklontz** [comment]
A Qt independent version would require a complete re-write.
