### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [biometrics/openbr#470]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [br_iterate_utemplates_file](https://github.com/biometrics/openbr/blob/34a914c4851ab0464d418b1db318b45e67fed109/openbr/universal_template.cpp#L80)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [statGallery destructor](https://github.com/biometrics/openbr/blob/34a914c4851ab0464d418b1db318b45e67fed109/openbr/plugins/gallery/stat.cpp#L44)

**Comment by sklum** [comment]
@elfring Can you expand on the functionality you'd like to see?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by sklum** [comment]
Although I didn't not write this code, my understanding is that the memory allocated by the `malloc` you reference is sufficiently checked by the subsequent `read_buffer` call (specifically, the `ferror` function).

With respect to the `printf` you mention, I assume you're referring to checking the number of bytes printed is what we'd expect.  I don't think this is standard practice.  However, if you'd like to make a PR with the changes you'd like to see, I'm happy to review it.

Regarding the static source code analysis, I don't have experience with this other than using proxy tools like valgrind.  Again, if you'd like to perform this analysis and let us know what you find, we would welcome it!

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by sklum** [comment]
Our Qt related exception handling is already sufficiently encapsulated to my satisfaction.  See https://github.com/biometrics/openbr/blob/dfc941ad1ffb27861e9111d4a12c295daf47a427/openbr/openbr_plugin.cpp#L1391.  Again, if there are changes you'd like to see, we'd welcome a PR.

**Comment by elfring** [comment]
Is there any source code left over where the exception handling is still incomplete so far?

**Comment by sklum** [comment]
In all likelihood, yes, but I wouldn't be able to point you to anything specific.
