### ISSUE TITLE
Running examples problems 

### ISSUE THREAD

**Issue by Peterosh** [biometrics/openbr#474]
I use opecv to obtain frame to Enroll template.
The console will output “nothing to happening”.
No one inside the video, but the output of age and Gender.
# include <QtCore/QCoreApplication>
# include <openbr/openbr_plugin.h>
# include "opencv2\opencv.hpp"

using namespace cv;
int main(int argc, char *argv[])
{

```
QCoreApplication a(argc, argv);


bool aa = br::Context::checkSDKPath("C:\\openbr\\build-msvc2013\\install");
br::Context::initialize(argc, argv, "C:\\openbr\\build-msvc2013\\install", false);

// Retrieve class for enrolling templates using the AgeEstimation algorithm
QSharedPointer<br::Transform> Age = br::Transform::fromAlgorithm("AgeEstimation",false);
QSharedPointer<br::Transform> Gender = br::Transform::fromAlgorithm("GenderEstimation");

VideoCapture capture(0);
Mat frame;
while (true)
{

    capture >> frame;
    if (*frame.size.p == 0)
    {
        continue;
    }
    imshow("one", frame);
    waitKey(30);
    // Initialize templates
    br::Template queryA(frame);
    br::Template queryB(frame);
    // Enroll templates
    queryA >> *Age;
    queryB >> *Gender;
    printf("%s age: %d\n", qPrintable(queryA.file.fileName()), int(queryA.file.get<float>("Age")));
    printf("%s gender: %s\n", qPrintable(queryB.file.fileName()), qPrintable(queryB.file.get<QString>("Gender")));

}
br::Context::finalize();
```

}

Forgive my poor English, I just want to find the answer. looool~

**Comment by sklum** [comment]
It sounds like you're concerned that OpenBR is outputting an age and gender when there is no person in the video?  If so, look into `enrollAll` which is the global boolean that controls, among other things, whether or not a template is generated when face detection fails.
