### ISSUE TITLE
unable to build openbr with opencv 3.1.0

### ISSUE THREAD

**Issue by harshmunshi** [biometrics/openbr#479]
Hi I am using opencv 3.1 and I am unable to build openbr. I'm getting the following error

CMake Error at /usr/share/OpenCV/OpenCVModules.cmake:117 (message):
  The imported target "opencv_core" references the file

     "/usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.8"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/OpenCV/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/share/OpenCV/OpenCVConfig.cmake:45 (include)
  CMakeLists.txt:88 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/harsh/openbr/build/CMakeFiles/CMakeOutput.log".

**Comment by jklontz** [comment]
We only support opencv 2.x
