### ISSUE TITLE
Gallery Append

### ISSUE THREAD

**Issue by sklum** [biometrics/openbr#488]
@caotto When you have some free time, could you fix the Gallery `append` option?  I believe it was broken when we switched to using `StreamTransform` for enrollment.  At the moment, based on my understanding, adding the `append` option only skips writing a template to the gallery that's already in the gallery whereas I'd like it to skip passing the a template through the given algorithm.

**Comment by caotto** [comment]
So, the problem isn't functional but efficiency thing (i.e. you want to avoid doing processing on images already present in gallery?) 

It should be pretty easy, this is currently handled here:
https://github.com/biometrics/openbr/blob/master/openbr/core/core.cpp#L212
where FileExclusion is the thing that removes overlap filenames.

It's currently placed at the endpoint, but it should be as simple as making a FileExclusion transform, and combining it with the normal pipeline (at the beginning) with 
https://github.com/biometrics/openbr/blob/master/openbr/openbr_plugin.h#L940

Anyway, I can do it but don't have time till a little later this week

**Comment by sklum** [comment]
Exactly.  Glad to hear it's a simple fix - no rush!

**Comment by sklum** [comment]
Done!
