### ISSUE TITLE
Training of Gender Classifier Error using OpenBR-0.5.0-win64.EXE

### ISSUE THREAD

**Issue by francissat** [biometrics/openbr#498]
Hi, 
I was not able to generate own training classifier for gender estimation by using the OpenBR-0.5.0-win64.EXE. Why it is not supporting? Let me know whether any new release is available version 5.0?

**Comment by sklum** [comment]
@francissat Without more detail, I can't help here.  You should be able to train a gender classifier (or any other type of classifier).
