### ISSUE TITLE
Copy-Paste Error in cropfromlandmarks.cpp

### ISSUE THREAD

**Issue by pakwan** [biometrics/openbr#499]
I found a bug (+solution):
rect.width() should be rect.height() in [cropfromlandmarks.cpp (Line 58)](https://github.com/biometrics/openbr/blob/master/openbr/plugins/imgproc/cropfromlandmarks.cpp#L58).
This causes errors like the following if an image should be cropped on which a face with a bigger height than the image itself is shown.

`OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /opencv-2.4.11/modules/core/src/matrix.cpp, line 323
Warning: Exception triggered when processing test/361.png[Confidence=-3.40282e+38, FrameNumber=0, FrontalFace=(0,0,48,48), Points=[(13,12), (11,18), (10,25), (9,32), (12,37), (15,43), (19,45), (25,45), (32,42), (37,38), (41,33), (43,27), (45,22), (39,5), (32,2), (25,1), (24,11), (20,10), (17,11), (20,12), (23,13), (26,14), (32,16), (36,16), (39,16), (42,19), (39,19), (36,18), (36,18), (22,14), (24,16), (23,15), (22,14), (21,14), (19,14), (20,15), (21,16), (23,16), (22,15), (36,20), (33,19), (34,19), (36,19), (37,19), (38,20), (36,21), (35,21), (34,20), (29,24), (26,23), (24,22), (21,27), (24,28), (28,29), (31,28), (29,30), (24,30), (20,27), (20,24), (15,31), (18,32), (21,33), (22,34), (24,34), (27,35), (30,36), (26,36), (22,35), (19,34), (19,34), (22,36), (26,36), (27,38), (24,38), (21,38), (18,36), (16,34)], Rects=[(0,0,48,48)], StasmLeftEye=(36,20), StasmRightEye=(22,15)] with transform CropFromLandmarks
  SDK Path: [...]
  File:  [...]/openbr/openbr_plugin.cpp
  Function: void _project(const br::Transform*, const br::Template*, br::Template*)
  Line: 1637`

**Comment by jklontz** [comment]
Thanks!
