### ISSUE TITLE
Impossibile to Build OpenBR - CMake Error at CMakeLists.txt:88 (find_package)

### ISSUE THREAD

**Issue by cix85** [biometrics/openbr#503]
Hi, 

i m following this guide: http://openbiometrics.org/docs/install/index.html#windows

At the point 6.Build OpenBR! it shows me an error, i post the entire shell:

![image](https://cloud.githubusercontent.com/assets/22657051/19148122/897f1be8-8bbb-11e6-8107-18ce9362fea1.png)
![image](https://cloud.githubusercontent.com/assets/22657051/19148159/b2a08516-8bbb-11e6-8594-cfcf9450a2d8.png)
![image](https://cloud.githubusercontent.com/assets/22657051/19148197/d2b4c93e-8bbb-11e6-9a3f-5194e7ceeff8.png)

Can anyone help me please??
Thanks

**Comment by EWER115** [comment]
You are missing Qt, try qmake --version to get the version of Qt present in your system. If there is no Qt installed with:

sudo apt-get install qt5-default libqt5svg5-dev qtcreator

**Comment by sklum** [comment]
@cix85 This error typically shows up when you're pointing `cmake` to an incorrect location for `Qt` and `OpenCV`.  Can you confirm that they are in the locations you've listed?

I'm going to close this issue for now but feel free to followup if you have more questions.
