### ISSUE TITLE
Working for arch?

### ISSUE THREAD

**Issue by jakehm** [biometrics/openbr#512]
Is this currently working for Arch for anyone?

The problem I'm running into is this:
To build openbr, you need opencv stable.
I can't build opencv stable (2.4?) on Arch, because it I get this error:
`/usr/include/c++/6.2.1/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
`
caused by gcc6+.

Opencv dev 3.? works with gcc6+ but opencv stable doesn't.
And Openbr isn't compatible with opencv 3.1 as far as I know.

**Comment by EWER115** [comment]
Simply downgrade compiler to for example 5.4 which is used as default in ubuntu 16.04.

**Comment by sklum** [comment]
@jakehm: I don't believe anyone on the core development team has tried to get OpenBR working on Arch, but I believe in theory you should be able to get things to work if you're able to select compilers/etc.  You're correct in that OpenBR isn't yet compatible with OpenCV 3.*, but we hope to remedy this sometime soon (and I believe there might be a branch where this work is already taking place?).
