### ISSUE TITLE
IMPORTANT (Multi_Thread age-gender estimation using openbr make Deadlock)

### ISSUE THREAD

**Issue by ahmadi219** [biometrics/openbr#514]
Hi
in a program i have producer thread that get frames from camera and put them in buffer
consumer read buffer and for each face in it run age-thread and gender-thread 
so for example 2 face  ---> 2 age-thread  2 gender-thread
for more than one face, the consumer stops suddenly.
we cant see this stop in 2 face or 3 face in beginning of run, but in 5 face we can observe this state faster!!!

**Comment by sklum** [comment]
It's unclear how I can help here @ahmadi219, but if you're able to give more specifics I can try to help.
