### ISSUE TITLE
OpenCV_FOUND to FALSE so package "OpenCV" when building on windows

### ISSUE THREAD

**Issue by MiguelMotaG** [biometrics/openbr#516]
Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:88 (find_package)

Hi, I'm getting the next eerror when trying to build in windows. I'm following the instructions from http://openbiometrics.org/docs/install/index.html#windows
and everything works ok until I tried to run 

cmake -G "CodeBlocks - NMake Makefiles" -DCMAKE_PREFIX_PATH="C:\opencv-2.4.11\build-msvc2015\install\bin;C:/Qt/Qt5.4.1/5.4/msvc2013_64" -DCMAKE_INSTALL_PREFIX="./install" -DBR_INSTALL_DEPENDENCIES=ON -DCMAKE_BUILD_TYPE=Debug ..

Any help will be be appretiated:

The error is the next:

CMake Error at CMakeLists.txt:88 (find_package):
  Found package configuration file:

    C:/opencv-2.4.11/build-msvc2015/install/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!

**Comment by MiguelMotaG** [comment]
it looks like the problem is in openCV, I'm getting 

--------------
CMake Warning at C:/opencv-2.4.11/build-msvc2015/install/OpenCVConfig.cmake:161 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.
-------------------

Is this a problem with open cv compilation?

**Comment by sklum** [comment]
@MiguelMotaG I'm assuming based on your other issue that you got this to work, but this isn't an OpenCV compilation error (AFAIK), but instead that CMake can't find your build of OpenCV.

Your `cmake` call is slightly different than what we list in the installation documentation:
`cmake -G "CodeBlocks - NMake Makefiles" -DCMAKE_PREFIX_PATH="C:/opencv-2.4.11/build/install;C:/Qt/Qt5.4.1/5.4/msvc2013_64" -DCMAKE_INSTALL_PREFIX="./install" -DBR_INSTALL_DEPENDENCIES=ON -DCMAKE_BUILD_TYPE=Release ..`  Note that we point to `build/install` and not `build/install/bin`.  Also, it looks like you might be mixing compiler versions.

Gunna close this but feel free to let me know if this doesn't help.
