### ISSUE TITLE
ICAO 9303 Compliant 

### ISSUE THREAD

**Issue by creativethinker** [biometrics/openbr#518]
I'v faced with a project for facial recognition and signature based on ICAO 9303 and I'm eager to use your library, so please let me know the followings:
1- what is the compliant percentage of your project with this standard?
2- Is there any plan to cover biometric parts of this standard?
Sincerely Yours,

**Comment by sklum** [comment]
@creativethinker I'm not familiar with the ICAO 9303 standard, nor have I heard any of the other core developers discussing it previously.  I'm happy to answer any specific question but my guess is that none of the project was designed with this standard in mind (which is not to say that OpenBR does not meet some of the criteria therein).
